apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry
  namespace: open-telemetry
spec:
  releaseName: open-telemetry
  chart:
    spec:
      chart: opentelemetry-demo
      version: '0.34.2'
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
  interval: 50m
  install:
    remediation:
      retries: 3